spring.application.name=validation-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8989

# Swagger OpenAPI config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
